### ISSUE TITLE
Empty 

### ISSUE THREAD

**Issue by sushiljain1989** [frenetic-lang/manual#2]
I am trying this example on frenetic-vm with 4 hosts but it is returning me nothing.

**Comment by craig-riecke** [comment]
Which example?

**Comment by sushiljain1989** [comment]
https://github.com/frenetic-lang/manual/blob/master/programmers_guide/code/netkat_principles/repeater3.py

**Comment by craig-riecke** [comment]
Repeater3.py is not supposed to work as a repeater.  It's just an intermediate example to illustrate the `connected()` hook.  Repeater4.py, which completes the illustration, will actually repeat packets.

**Comment by sushiljain1989** [comment]
I am not interested in functionality right now. What I am interested in is, **Switches and their port** lists. When I am calling `current_switches()`, it returns me empty list/dic and looks like this :

`Connected to Frenetic - Switches: {}`

Screenshots, in case it is needed : 

![virtualbox_frenetic-uservm-x86_64-20160610_04_10_2016_18_04_59](https://cloud.githubusercontent.com/assets/4305242/19082192/5b1f0e52-8a5d-11e6-8df3-8c42676315c3.png)
![virtualbox_frenetic-uservm-x86_64-20160610_04_10_2016_18_04_42](https://cloud.githubusercontent.com/assets/4305242/19082193/5b22261e-8a5d-11e6-8e0d-d62605bfec70.png)
![virtualbox_frenetic-uservm-x86_64-20160610_04_10_2016_18_07_54](https://cloud.githubusercontent.com/assets/4305242/19082224/81a68d2a-8a5d-11e6-9e35-2701cd7e16dd.png)

**Comment by sushiljain1989** [comment]
I just tried running repeater4.py. It is giving me error and it seems that this error is because of absence of switch
![virtualbox_frenetic-uservm-x86_64-20160610_04_10_2016_18_21_56](https://cloud.githubusercontent.com/assets/4305242/19082728/a91ae458-8a5f-11e6-84b0-53b4d68cabee.png)

**Comment by craig-riecke** [comment]
Thank you - that's helpful!  It looks like Mininet's default behavior may have changed.  When it didn't find a controller at ports 6633 (Openflow 1.0 port) and port 6653 (Openflow 1.3 port), it defaulted to trying 6653.  Frenetic currently only works with port 6633.  It might work to start Frenetic first, then Mininet (it should say it's connected on port 6633), then the Python app.

**Comment by sushiljain1989** [comment]
Wow, it worked for me. Thanks a lot !
